create table COCKTAIL (
  ID UUID PRIMARY KEY,
  ID_DRINK TEXT,
  NAME TEXT,
  INGREDIENTS TEXT
);

create table COCKTAIL_SHOPPING_LIST (
  COCKTAIL_ID UUID,
  SHOPPING_LIST_ID UUID,
  FOREIGN KEY (COCKTAIL_ID) REFERENCES COCKTAIL(ID),
  FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID)
)
